### PR TITLE
Add: left=>right split, Kobo Aura h2o and fix natsort sorting

### PR DESCRIPTION
**Pull request by naparuba**
* Add: split option from left then right to manage some mangas
* Add: the Kobo Aura H2o ereader (special resolution)
* Fix: remove natsort dependency and use a custom function instead for
natural sorting

### CODE REVIEW

**Comment by naparuba** [comment]
Here is the code to mainly add the left then right split and fix natural sorting

And also manage my personnal ereader ^^ (other resolution than kindle ones)

I'm looking how to generate the .exe, if you have documentation about it, I'm interested :)

**Comment by FooSoft** [comment]
Merged :+1: 

As far as the executable goes, all you have to do is download Py2Exe and run the `setup.py` file in the root dir.

**Comment by naparuba** [comment]
Hi,

Seems that py2exe and win64 is not working well. I have a windows 32 at
home, will build from there :)

Ps: I did send another PR because I forgot to reference the new
img/book.png in the setup.py file.

**Comment by FooSoft** [comment]
Yeah, I think you have to have 32 bit installs of python and all the libs. Packaging on Windows is annoying.

**Pull request merged**
